#ifndef _ASSEMBLY_SCAUSE_H_
#define _ASSEMBLY_SCAUSE_H_

#define SCAUSE_INTERRUPT (1UL << 63)
#define SCAUSE_EXCEPTION_CODE ((1UL << 63) - 1)
#define SCAUSE_USER_SOFTWARE 0
#define SCAUSE_SUPERVISOR_SOFRWARE 1
#define SCAUSE_USER_TIMER 4
#define SCAUSE_SUPERVISOR_TIMER 5
#define SCAUSE_USER_EXTERNAL 8
#define SCAUSE_SUPERVISOR_EXTERNAL 9

#define SCAUSE_ENVIRONMENT_CALL 8
#define SCAUSE_LOAD_PAGE_FAULT 13
#define SCAUSE_STORE_PAGE_FAULT 15

#endif
