./runtest.exe -w entry-static.exe rlimit_open_files
./runtest.exe -w entry-static.exe stat
./runtest.exe -w entry-static.exe fgetwc_buffering
./runtest.exe -w entry-static.exe fflush_exit
./runtest.exe -w entry-static.exe utime
./runtest.exe -w entry-static.exe strptime
./runtest.exe -w entry-static.exe setjmp
./runtest.exe -w entry-static.exe search_hsearch
./runtest.exe -w entry-static.exe pthread_cancel
./runtest.exe -w entry-static.exe pthread_cond_smasher