./runtest.exe -w entry-static.exe pthread_cancel_points
./runtest.exe -w entry-static.exe pthread_cancel
./runtest.exe -w entry-static.exe pthread_cond
./runtest.exe -w entry-static.exe pthread_tsd
./runtest.exe -w entry-static.exe search_hsearch
./runtest.exe -w entry-static.exe setjmp
./runtest.exe -w entry-static.exe stat
./runtest.exe -w entry-static.exe strptime
./runtest.exe -w entry-static.exe ungetc
./runtest.exe -w entry-static.exe utime
./runtest.exe -w entry-static.exe daemon_failure
./runtest.exe -w entry-static.exe fflush_exit
./runtest.exe -w entry-static.exe fgetwc_buffering
./runtest.exe -w entry-static.exe ftello_unflushed_append
./runtest.exe -w entry-static.exe pthread_robust_detach
./runtest.exe -w entry-static.exe pthread_cancel_sem_wait
./runtest.exe -w entry-static.exe pthread_cond_smasher
./runtest.exe -w entry-static.exe pthread_condattr_setclock
./runtest.exe -w entry-static.exe pthread_exit_cancel
./runtest.exe -w entry-static.exe pthread_once_deadlock
./runtest.exe -w entry-static.exe pthread_rwlock_ebusy
./runtest.exe -w entry-static.exe rlimit_open_files
./runtest.exe -w entry-static.exe statvfs
