#ifndef _INODE_H_
#define _INODE_H_

#include "Type.h"

#define INODE_NUM 1024
#define INODE_ITEM_NUM 64
typedef struct Inode {
    u32 item[INODE_ITEM_NUM];
} Inode;

#define INODE_SECOND_ITEM_BASE 8
#define INODE_THIRD_ITEM_BASE 24

#define INODE_SECOND_LEVEL_BOTTOM INODE_SECOND_ITEM_BASE
#define INODE_SECOND_LEVEL_TOP (INODE_SECOND_LEVEL_BOTTOM + (INODE_THIRD_ITEM_BASE - INODE_SECOND_ITEM_BASE) * INODE_ITEM_NUM)
#define INODE_THIRD_LEVEL_BOTTOM INODE_SECOND_LEVEL_TOP
#define INODE_THIRD_LEVEL_TOP (INODE_THIRD_LEVEL_BOTTOM + (INODE_ITEM_NUM - INODE_THIRD_ITEM_BASE) * INODE_ITEM_NUM * INODE_ITEM_NUM)

int inodeAlloc();
void inodeFree(int i);

#endif
