#ifndef _SYSCALL_ID_H_
#define _SYSCALL_ID_H_

#define SYSCALL_PUTCHAR 0
#define SYSCALL_GET_PROCESS_ID 1
#define SYSCALL_YIELD 2
#define SYSCALL_PROCESS_DESTORY 3
#define SYSCALL_FORK 4
#define SYSCALL_PUT_STRING 5
#define SYSCALL_OPEN 6
#define SYSCALL_READ 7
#define SYSCALL_WRITE 8
#define SYSCALL_CLOSE 9

#endif